apiVersion: v1
kind: Service
metadata:
  name: php2
  labels:
    tier: backend
spec:
  selector:
    app: php2
    tier: backend
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php2
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php2
      tier: backend
  template:
    metadata:
      labels:
        app: php2
        tier: backend
    spec:
      volumes:
      - name: code2
        persistentVolumeClaim:
          claimName: code2
      containers:
      - name: php2
#        image: php:7-fpm
        image: sjmax/php-7.1-fpm
        volumeMounts:
        - name: code2
          mountPath: /code2
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: code2
          mountPath: /code2
